"""Quality gate thresholds and shared types.

Generated by /quality-init on 2026-07-14 18:41 UTC.
Calibrated from project metrics — edit these values to tune sensitivity.

Each threshold shows its source:
  - "p90 = N" means the 90th percentile of existing code was N.
  - "floor = N" means the minimum acceptable threshold.
  - The higher of (p90, floor) is used as the threshold.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

# ── Thresholds ────────────────────────────────────────────────────────
# # max_complexity: no measurements, using floor = 10
# max_function_lines: no measurements, using floor = 20
# max_nesting_depth: no measurements, using floor = 3
# max_parameters: no measurements, using floor = 4
# max_file_lines: p90 = 163, floor = 300 -> using floor
# Calibrated from 237 source files

MAX_COMPLEXITY: int = 10
MAX_FUNCTION_LINES: int = 20
MAX_NESTING_DEPTH: int = 3
MAX_PARAMETERS: int = 4
MAX_FILE_LINES: int = 300
DUPLICATE_MIN_LINES: int = 4
DUPLICATE_MIN_OCCURRENCES: int = 2

# ── Fix instructions ──────────────────────────────────────────────────

FIXES: dict[str, str] = {
    "complexity": "Use extract-method, early returns, guard clauses, or lookup tables.",
    "long_function": "Extract helper functions for distinct logical steps.",
    "deep_nesting": "Use guard clauses and early returns to flatten control flow.",
    "too_many_params": "Group related parameters into a dataclass or options object.",
    "duplicate_block": "Extract repeated code into a shared helper function.",
    "long_file": "Split into smaller modules with clear single responsibilities.",
}

# ── Skip directories ─────────────────────────────────────────────────

SKIP_DIRS: frozenset[str] = frozenset((
    ".cache",
    ".egg-info",
    ".git",
    ".mypy_cache",
    ".next",
    ".nyc_output",
    ".parcel-cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".turbo",
    ".venv",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "eggs",
    "node_modules",
    "target",
    "vendor",
    "venv",
    # Detected test directories (uncomment to skip):
    # "test",
))

# ── Supported extensions ──────────────────────────────────────────────

PYTHON_EXTENSIONS: frozenset[str] = frozenset((".py",))

LIZARD_EXTENSIONS: frozenset[str] = frozenset((
    ".js", ".jsx", ".ts", ".tsx", ".java",
    ".go", ".rs", ".c", ".cpp", ".cc", ".cs",
))

# ── Data classes ──────────────────────────────────────────────────────


@dataclass
class Smell:
    """A single code smell finding."""

    kind: str
    detail: str
    fix: str
    line: Optional[int] = None
    function_name: Optional[str] = None
